# Generated by Django 4.2.3 on 2023-07-25 05:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('novapp', '0003_alter_doctor_dob'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctor',
            name='address',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='doctor',
            name='department',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='novapp.department'),
        ),
        migrations.AlterField(
            model_name='doctor',
            name='dob',
            field=models.CharField(max_length=14, null=True),
        ),
        migrations.AlterField(
            model_name='doctor',
            name='mobileno',
            field=models.CharField(max_length=13, null=True),
        ),
        migrations.AlterField(
            model_name='doctor',
            name='profile_pic',
            field=models.ImageField(null=True, upload_to='doctorprofile/'),
        ),
        migrations.AlterField(
            model_name='doctor',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
