# Generated by Django 4.2.3 on 2023-07-25 11:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('novapp', '0004_alter_doctor_address_alter_doctor_department_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='admitDate',
            field=models.DateField(auto_now_add=True),
        ),
    ]
