# Generated by Django 4.2.3 on 2023-07-25 18:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('novapp', '0005_alter_patient_admitdate'),
    ]

    operations = [
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('patientName', models.CharField(max_length=50)),
                ('doctorName', models.CharField(max_length=50)),
                ('age', models.PositiveBigIntegerField()),
                ('appointmentBookDate', models.DateField(auto_now_add=True)),
                ('appointmentDate', models.DateField()),
                ('message', models.TextField(max_length=500)),
                ('status', models.BooleanField(default=False)),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='novapp.department')),
            ],
        ),
    ]
