# Generated by Django 4.2.3 on 2023-07-25 18:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('novapp', '0006_appointment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='doctorName',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='novapp.doctor'),
        ),
    ]
