# Generated by Django 4.2.3 on 2023-07-25 19:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('novapp', '0007_alter_appointment_doctorname'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='address',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
