# Generated by Django 4.2.3 on 2023-07-26 04:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('novapp', '0008_appointment_address'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctor',
            name='dob',
            field=models.DateField(max_length=14, null=True),
        ),
    ]
