# Generated by Django 4.2.3 on 2023-07-26 04:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('novapp', '0009_alter_doctor_dob'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='dob',
            field=models.DateField(max_length=14, null=True),
        ),
    ]
