# Generated by Django 4.2.3 on 2023-07-26 16:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('novapp', '0010_alter_patient_dob'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='email',
            field=models.EmailField(max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='appointment',
            name='mobileNo',
            field=models.CharField(max_length=15, null=True),
        ),
    ]
